<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jb-5f-d079" name="Default test" tests="1" failures="1" timestamp="29 Jan 2016 12:28:00 GMT" time="125.71" errors="0">
  <testcase name="expensetest" time="90.082" classname="scripts.com.vapprove.Expenses">
    <failure type="java.lang.AssertionError" message="command:The element of a command &amp;quot;click&amp;quot; not found||description:The element of a command &amp;quot;click&amp;quot; not found at step : 3 : on the displayed page||Fail">
      <![CDATA[java.lang.AssertionError: command:The element of a command "click" not found||description:The element of a command "click" not found at step : 3 : on the displayed page||Fail
	at com.thoughtworks.selenium.SeleneseTestBase.fail(SeleneseTestBase.java:393)
	at scripts.com.framework.FrameworkAPI.reportStepDtlsWithScreenshot(FrameworkAPI.java:384)
	at scripts.com.framework.FrameworkAPI.reportElementNotFound(FrameworkAPI.java:2001)
	at scripts.com.framework.FrameworkAPI.perform(FrameworkAPI.java:1485)
	at scripts.com.vapprove.Expenses.expensetest(Expenses.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- expensetest -->
</testsuite> <!-- Default test -->
